dbt_hr:
  outputs:
    dev:
      dataset: hr_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: hr-data-470216
      threads: 4
      type: bigquery
  target: dev

